### ISSUE TITLE
HMVC

### ISSUE THREAD

**Issue by Andrewsuares** [bakeiro/Light-PHP#1]
Interesting project. Any plans to add HMVC support? How hard would it be to import a project from CI to this?

**Comment by bakeiro** [comment]
For the time being, I don't have any plans to add HMVC support, (I don't know exactly how big/small would be the change)
CI (do you mean Code Igniter?) I don't know how hard would be to move a project from Code Igniter (obviously, it depends of the project) I guess you can try with a small test ;)
Also if you plan to import some project I can suggest you to use the library PHP-auth to save time and don't develop all the auth user functions (like Activate account, Resend activation email, Reset password etc...)
