### ISSUE TITLE
Util.php missing in system/engine

### ISSUE THREAD

**Issue by umefarooq** [bakeiro/Light-PHP#16]
Hi,
I was trying to install light-php with composer when it run post-install.php file it gives failed to open "./system/engine/Util.php". you need to update post-install file as you have moved Util.php file under library directory.

**Comment by bakeiro** [comment]
right! sorry, this is updated in the version 1.82, now should be working ;)

**Comment by bakeiro** [comment]
closing as now it's working, any question, u can write me ;)

**Comment by umefarooq** [comment]
i was trying to use this for a flat file cms and don't want to use mysql, json data as db, another thing form validation was not there in this that's i moved to Codeigniter, i will be happy to have validation class also

**Comment by bakeiro** [comment]
Well, this tries to be the most minimal possible, you have a lot of css/js frameworks for validating data, or you can find composer libraries for this
same for "don't want use mysql, json data as db" so you can import a library which does the job in this proyect ;)
