### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'ZipArchive' when `composer create-project bakeiro/light-php-site`

### ISSUE THREAD

**Issue by pierremzz** [bakeiro/Light-PHP#35]
Hi, I found `Uncaught Error: Class 'ZipArchive'` when trying to install light-php-site
```
$ composer create-project bakeiro/light-php-site

...

PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /home/user/light-php-site/get-source-code.php:6
Stack trace:
#0 Command line code(1): require_once()
#1 {main}
  thrown in /home/user/light-php-site/get-source-code.php on line 6
Script php -r "require_once('./get-source-code.php'); " handling the post-create-project-cmd event returned with error code 255
```

edit: I run Ubuntu 20.04 LTS

**Comment by bakeiro** [comment]
Ah I see!, I think you don't have installed the class ZIP for your PHP env, I will have a look at that, anyhow, this it's the repo of light-PHP not light-PHP-site, but thanks for your feedback!

**Comment by bakeiro** [comment]
closing since it's a lack of dependency error (related with the SO, not the framework itself)
