### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by suhaimim** [bakeiro/Light-PHP#37]
![Screenshot_20220131-094521_Chrome](https://user-images.githubusercontent.com/35832684/151728324-cfc16fc9-cafd-4914-b06b-b9ab611fb533.jpg)

**Comment by suhaimim** [comment]
![Uploading Screenshot_20220131-110940_Chrome.jpg…]()

**Comment by suhaimim** [comment]
![Screenshot_20220131-110940_Chrome](https://user-images.githubusercontent.com/35832684/151733991-e98548f3-8978-4d24-8bcf-2cc4dfe35ef9.jpg)

**Comment by suhaimim** [comment]
👆 after change composer.json php 7.0 to 8.0

**Comment by bakeiro** [comment]
I see... sorry for the late reply, the project it's a bit unmaintained, first error seems that you didn't execute composer install (are you just cloning repo and trying to use it?)

second error it's that this framework it's not yet ready with php 8, might be in the future let's see

**Comment by bakeiro** [comment]
solved now, if happens again, feel free to open it again ;)
