### ISSUE TITLE
Fatal error: Default value for parameters with a class type can only be NULL in /Users/wlin/dev/light-php/system/library/Config.php on line 22

### ISSUE THREAD

**Issue by dotku** [bakeiro/Light-PHP#38]
**Describe the bug**

When I was trying to access the framework, I got error:

```
Fatal error: Default value for parameters with a class type can only be NULL in /Users/wlin/dev/light-php/system/library/Config.php on line 22
```

**To Reproduce**
1. Install and run the framework by the command:

    ```
    composer create-project bakeiro/light-php
    PHP -S localhost:8080 -t light-php/
    ```
  
2. boot the website by URL: http://localhost:8080/public/index.php?route=product/product/getProduct&prod_id=1

**Expected behavior**
No error with a hello world view on the page.

**Environment**
 - OS: MacOS
 - Browser: Chrome
 - PHP Version: 7.4
 - Light-PHP Version: 1.981.0.0

**Comment by bakeiro** [comment]
thanks for the bug! will try to fix this things when I have time, contact with you once it's done

**Comment by bakeiro** [comment]
Hi!
I just updated the codebase, and I solved some errors, can you confirm me if this error happens again? please try this to reproduce with the new code
```
composer create-project bakeiro/light-php:1.985
PHP -S localhost:8080 -t .\light-php\public\
```
