### ISSUE TITLE
Error when command 'composer create-project bakeiro/light-php-site'

### ISSUE THREAD

**Issue by john-banjirou** [bakeiro/Light-PHP#42]
**Describe the bug**
Here below is the error.

---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------

Creating a "bakeiro/light-php-site" project at "./light-php-site"
Info from https://repo.packagist.org: #StandWithUkraine
Cannot use bakeiro/light-php-site's latest version 0.96 as it requires php ^7.0 which is not satisfied by your platform.
Installing bakeiro/light-php-site (0.9)
  - Installing bakeiro/light-php-site (0.9): Extracting archive
Created project in C:\xampp\htdocs\naoki\php\112022-light\light-php-site
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bakeiro/micro_php_template_engine, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------

**Enviroment**
 - OS:windows
 - 
**Additional context**
it looks like related to bakeiro/micro_php_template_engine and     "minimum-stability": "stable",

Any idea anyone?

**Comment by john-banjirou** [comment]
happy to say i resolved it myself.

it is php version.
I downgrade it 8.* to 7.* and it is going away.

I suppose that is it...

**Comment by bakeiro** [comment]
hey!
Sorry for late reply, this is a light-php-site error, not a light-php error, still, that package it's a bit outdated, not yet ported to PHP 8, guess it's working now? (to know if I can close the issue)

**Comment by bakeiro** [comment]
btw, it's updated now for the version 8.2 ;) (at least light-php, **not** light-php-site)
